# Generated by Django 5.0.4 on 2024-05-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите категорию продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                help_text="Введите описание продукта",
                max_length=100,
                verbose_name="Описание",
            ),
        ),
    ]
