# Generated by Django 5.0.4 on 2024-06-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_version_number_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number_version",
            field=models.IntegerField(default=0, verbose_name="Номер версии"),
        ),
    ]
