# Generated by Django 5.0.4 on 2024-06-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner"),
        ("catalog", "0006_product_owner"),
    ]

    operations = []
